<!-- 
# Installing Next.js
Next.js is a popular React framework that enables you to build server-side rendered (SSR) applications, static websites, and more. It provides a powerful set of features such as routing, API routes, and built-in CSS support. In this section, we will go through the steps to install Next.js and create a simple Next.js application.
 -->

<!-- ###NEXT.JS PACKAGE INSTALLATION### -->

<!-- 0. Create a new file in the same directory as the html file called package.json. -->

<!-- 1. To install Next.js, you will need to have Node.js and npm (Node Package Manager) installed on your machine. 
Once you have those installed, you can create a new Next.js application using the following command:

npm install react@latest react-dom@latest next@latest
 -->

<!-- 2. After running the above command, you will have the latest versions of React, ReactDOM, and Next.js installed in your project. You can check your package.json file to see the installed packages and their versions. A package-lock.json file will also be generated with detailed information on the versions of each package (next, react, react-dom) that was installed.  DO NOT EDIT THIS FILE, it is edited automatically -->

<!--  3. With next.js and react installed the html can be simplified to the following. This is a simple Next.js application that will render a page with a header and a list of names. The code below will be in a file called index.js inside a folder called pages.  There are tags that will no longer be needed and will be commented out.  -->


<!-- imports go at the top of your file and will import code (or libraries) from other files. In this case, we are importing the useState hook from the React library. This allows us to use state in our functional component. -->
import { useState } from 'react';

<!-- <html> -->
  <!-- <body> -->
    <!-- <div id="app"></div> -->
    <!-- <script src="https://unpkg.com/react@18/umd/react.development.js"></script> -->
    <!-- <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script> -->
    <!-- <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script> -->

    <!-- <script type="text/jsx"> -->
        function Header({ title }) {
            console.log(title);
            return <h1>{title}</h1>;
        }

        function HomePage() {
            const names = ['Ada Lovelace', 'Grace Hopper', 'Marie Curie', 'Rosalind Franklin'];
            const [likes, setLikes] = {/*React.*/}useState(0);

            function handleClick() {
                setLikes(likes + 1)
            }
                return (
                    <div>
                        <Header title="Develop. Preview. Ship" />
                            <ul>
                                {names.map((name) => (
                                <li key={name}>{name}</li>
                                ))}
                            </ul>
                        <button onClick={handleClick}>Like({likes})</button>
                    </div>
                );
            }
        const root = ReactDOM.createRoot(app);
        root.render(<HomePage />);
    <!-- </script> -->
<!-- </body> -->
<!-- </html>  -->
