/* 
# layout.js 
This file is used to define the layout of your application. It wraps around all the pages in your application and provides a consistent layout across all pages. You can use this file to add global styles, meta tags, and other elements that should be present on all pages.
*/


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
